# Generated by Django 4.2.7 on 2025-06-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_remove_car_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
    ]
