# Generated by Django 5.2.2 on 2025-06-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for this car', max_length=20),
        ),
    ]
